import type { Metadata } from 'next';

export const GUIDE_PUBLISHED_DATE = '2026-08-01';
export const GUIDE_DISPLAY_DATE = 'August 1, 2026';

export const blogGuides = [
  {
    slug: 'compress-image-online-guide',
    title: 'How to Compress an Image Without Making It Look Bad',
    description: 'Learn what actually reduces image file size, how compression differs from resizing, and how to balance quality with practical upload and website requirements.',
    category: 'Images',
    readTime: '8 min',
    marker: 'The best compressed image is small enough for the job and still looks right',
    image: '/images/compress-image-online-simplifyconvert.webp',
    imageAlt: 'SimplifyConvert online image compression tool for reducing image file size',
  },
  {
    slug: 'remove-background-online-guide',
    title: 'How Background Removal Works and Why Some Images Are Harder Than Others',
    description: 'Understand how image background removal works, what makes clean cutouts difficult, and how to review transparent images before using them.',
    category: 'Images',
    readTime: '8 min',
    marker: 'Good background removal depends on both the subject and the original image',
    image: '/images/remove-background-online-simplifyconvert.webp',
    imageAlt: 'SimplifyConvert background removal tool for creating transparent image backgrounds',
  },
  {
    slug: 'merge-pdf-online-guide',
    title: 'How to Merge PDF Files Without Losing Track of Page Order',
    description: 'Learn how to prepare multiple PDFs for merging, choose the correct page order, check the finished document, and avoid common document-combining mistakes.',
    category: 'PDF',
    readTime: '8 min',
    marker: 'A good merged PDF should feel like one intentional document',
    image: '/images/merge-pdf-online-simplifyconvert.webp',
    imageAlt: 'SimplifyConvert Merge PDF tool for combining multiple PDF documents',
  },
  {
    slug: 'video-tools-guide',
    title: 'Video Tools Explained: A Practical Guide to Converting and Working With Video',
    description: 'Understand common video tasks such as conversion, compression and editing, and learn what resolution, bitrate and format mean for the finished file.',
    category: 'Video',
    readTime: '9 min',
    marker: 'Video processing becomes easier when you know what should change',
    image: '/images/video-tools-simplifyconvert.webp',
    imageAlt: 'SimplifyConvert video tools for video conversion, compression and editing',
  },
  {
    slug: 'data-tools-guide',
    title: 'Data Conversion Tools Explained: CSV, Excel, JSON and Structured Files',
    description: 'Learn how common data formats differ and what to check when converting CSV, Excel, JSON and other structured files between systems.',
    category: 'Data',
    readTime: '9 min',
    marker: 'A successful data conversion preserves the meaning your next system needs',
    image: '/images/data-tools-simplifyconvert.webp',
    imageAlt: 'SimplifyConvert data tools for CSV, Excel, JSON and structured file conversion',
  },
  {
    slug: 'ai-presentation-maker-guide',
    title: 'How to Use an AI Presentation Maker Without Ending Up With Generic Slides',
    description: 'Learn how to turn a clear brief into a useful presentation draft, improve slide structure, and review AI-generated content before presenting it.',
    category: 'AI',
    readTime: '8 min',
    marker: 'A good presentation starts with a clear audience and purpose',
    image: '/images/ai-presentation-maker-simplifyconvert.webp',
    imageAlt: 'SimplifyConvert AI Presentation Maker for creating presentation drafts from a prompt',
  },
  {
    slug: 'ai-document-maker-guide',
    title: 'AI Document Maker: How to Turn a Rough Idea Into a Useful First Draft',
    description: 'Learn how to use an AI document maker for reports, proposals and structured drafts while keeping accuracy, tone and human review in the workflow.',
    category: 'AI',
    readTime: '8 min',
    marker: 'Use AI to get past the blank page, then make the document yours',
    image: '/images/ai-document-maker-simplifyconvert.webp',
    imageAlt: 'SimplifyConvert AI Document Maker for reports, proposals and structured drafts',
  },
  {
    slug: 'ai-spreadsheet-maker-guide',
    title: 'AI Spreadsheet Maker: Build a Better Spreadsheet by Describing the Job First',
    description: 'Learn how to generate a practical spreadsheet structure for budgets, trackers, inventories and planning, then review formulas and data before using it.',
    category: 'AI',
    readTime: '8 min',
    marker: 'Describe the workflow the spreadsheet must support, not just the columns',
    image: '/images/ai-spreadsheet-maker-simplifyconvert.webp',
    imageAlt: 'SimplifyConvert AI Spreadsheet Maker for creating structured spreadsheet drafts',
  },
  {
    slug: 'ai-studio-guide',
    title: 'What Is SimplifyConvert AI Studio and When Should You Use It?',
    description: 'Learn how AI Studio differs from traditional file converters and how presentation, document and spreadsheet generation fit into practical workflows.',
    category: 'AI',
    readTime: '8 min',
    marker: 'AI Studio creates a starting point that still deserves human review',
    image: '/images/ai-studio-simplifyconvert.webp',
    imageAlt: 'SimplifyConvert AI Studio for presentations, documents and spreadsheets',
  },
  {
    slug: 'all-tools-guide',
    title: 'A Practical Guide to SimplifyConvert Online Tools',
    description: 'Explore SimplifyConvert tools for PDFs, images, videos, data, documents and everyday file tasks, and learn how to choose the right tool for the job.',
    category: 'Platform',
    readTime: '8 min',
    marker: 'Find the tool that matches the task you actually need to complete',
    image: '/images/all-tools-simplifyconver.webp',
    imageAlt: 'SimplifyConvert online tools for PDF, image, video, data and file tasks',
  },
  {
    slug: 'pdf-tools-guide',
    title: 'PDF Tools Explained: Choosing the Right Tool for Your Document',
    description: 'Learn when to merge, split, compress, convert, edit or sign a PDF and how to choose the right PDF workflow for your document.',
    category: 'PDF',
    readTime: '9 min',
    marker: 'Different PDF problems need different PDF tools',
    image: '/images/pdf-tools-simplifyconvert.webp',
    imageAlt: 'SimplifyConvert PDF tools for editing, converting and managing PDF documents',
  },
  {
    slug: 'image-tools-guide',
    title: 'Image Tools Explained: Convert, Compress, Resize and Edit Images',
    description: 'Understand common image tasks including format conversion, compression, resizing and background editing so you can choose the right workflow.',
    category: 'Images',
    readTime: '9 min',
    marker: 'Choose an image operation based on what needs to change',
    image: '/images/image-tools-simplifyconvert.webp',
    imageAlt: 'SimplifyConvert image tools for converting, compressing, resizing and editing images',
  },
  {
    slug: 'how-simplifyconvert-works',
    title: 'How SimplifyConvert Works: A Guide to Online File and AI Tools',
    description: 'Learn how SimplifyConvert handles conversion, compression, editing, data workflows, and AI-assisted file creation from one online platform.',
    category: 'Platform',
    readTime: '9 min',
    marker: 'Choose the operation first, then choose the tool',
    image: '/images/How SimplifyConvert Works.webp',
    imageAlt: 'Overview of how SimplifyConvert online tools work',
  },
  {
    slug: 'merge-split-compress-ocr-pdf-guide',
    title: 'Merge vs Split vs Compress vs OCR: Which PDF Tool Should You Use?',
    description: 'Choose the right PDF operation by separating page organization, file-size reduction, text recognition, and editable-document needs.',
    category: 'PDF',
    readTime: '10 min',
    marker: 'A PDF workflow starts with the problem, not the button',
  },
  {
    slug: 'jpg-png-webp-avif-image-formats',
    title: 'JPG vs PNG vs WebP vs AVIF: Which Image Format Should You Use?',
    description: 'Compare four common image formats by compression, transparency, browser use, editing needs, and realistic file-size tradeoffs.',
    category: 'Images',
    readTime: '11 min',
    marker: 'There is no universally best image format',
  },
  {
    slug: 'image-compression-quality-file-size',
    title: 'How Image Compression Affects Quality, Dimensions and File Size',
    description: 'Understand how encoding quality, pixel dimensions, image content, and repeated recompression affect image size and appearance.',
    category: 'Images',
    readTime: '10 min',
    marker: 'Compression and resizing solve different problems',
  },
  {
    slug: 'csv-excel-json-data-formats',
    title: 'CSV vs Excel vs JSON: Which Data Format Should You Choose?',
    description: 'Select a data format by comparing flat tables, spreadsheet features, nested structures, data types, and conversion risks.',
    category: 'Data',
    readTime: '12 min',
    marker: 'The right data format depends on who or what must use it next',
  },
  {
    slug: 'video-compression-resolution-bitrate-codec',
    title: 'Video Compression Explained: Resolution, Bitrate, Codec and File Size',
    description: 'Make practical video compression decisions by understanding resolution, bitrate, codecs, containers, frame rate, and audio.',
    category: 'Video',
    readTime: '11 min',
    marker: 'Video size is the result of several interacting choices',
  },
] as const;

export const existingBlogGuide = {
  slug: 'jpg-to-png-conversion-guide',
  title: 'How to Convert JPG to PNG Without Losing Quality',
  description: 'Learn what changes—and what does not—when a JPEG image is re-encoded as PNG.',
  category: 'Images',
  readTime: '5 min',
  image: '/images/jpg-to-png-converter-simplifyconvert.webp',
  imageAlt: 'SimplifyConvert JPG to PNG converter for converting JPEG images to PNG',
} as const;

export function guideMetadata(slug: string): Metadata {
  const guide = blogGuides.find((item) => item.slug === slug);
  if (!guide) throw new Error(`Unknown editorial guide: ${slug}`);

  const url = `https://simplifyconvert.com/blog/${guide.slug}`;
  const image = 'image' in guide && typeof guide.image === 'string'
    ? `https://simplifyconvert.com${guide.image}`
    : undefined;
  return {
    title: guide.title,
    description: guide.description,
    authors: [{ name: 'SimplifyConvert' }],
    alternates: { canonical: url },
    openGraph: {
      type: 'article',
      locale: 'en_US',
      siteName: 'SimplifyConvert',
      url,
      title: guide.title,
      description: guide.description,
      publishedTime: `${GUIDE_PUBLISHED_DATE}T00:00:00+05:30`,
      ...(image ? { images: [{ url: image, alt: guide.title }] } : {}),
    },
    twitter: {
      card: 'summary',
      title: guide.title,
      description: guide.description,
      ...(image ? { images: [image] } : {}),
    },
  };
}
